language: php

php:
  - 5.6
  - 7.1

env:
  global:
    - PLUGIN_NAME=CakeBasicFunctions
    - REQUIRE=""

  matrix:
    - CAKE_VERSION=2.10

matrix:
  include:
    - php: 5.6
      env:
        - CAKE_REF=2.10.9
        - CODECOVERAGE=1
    - php: 5.6
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - CAKE_REF=2.10.11

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
